#!/usr/bin/env bash
# Write a bash script that displays the content of the file /etc/passwd

f="/etc/passwd"

while IFS=: read -r username userid homedir
do
	echo "$username, $userid, $homedir"
done < $f
