#!/usr/bin/env bash
# Write a Bash script that Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

pid_file="/var/run/myscript.pid"

cleanup() {
	echo "Deleting PID file and terminating the script"
	rm "$pid_file"
	exit
}

handle_interrupt() {
	
	echo "Y U no love me?!"
}
trap cleanup SIGTERM SIGQUIT
trap handle_interrupt SIGINT
	echo"I hate the kill command"

	echo "$$" > "$pid_file"
	echo "To infinity and beyond!"

while true
	do
		sleep 1
	done
