#!/usr/bin/env bash
# Write a manage_my_process Bash script that:

while true
do
	echo "I am alive!" >> /tmp/my_process
	sleep 2
done

case "$1" in
	start)
		/path/to/manage_my_process &
		echo $! > /var/run/my_process.pid
		echo "manage_my_process started"
		;;
	stop)
		kill  $(cat /var/run/my_process.pid) 
                rm /var/run/my_process.pid
                echo "manage_my_process stopped"
                ;;
	restart)
	       	kill $(cat /var/run/my_process.pid)
		 rm /var/run/my_process.pid
		 /path/to/manage_my_process &
		 echo $! > /var/run/my_process.pid
		 echo "manage_my_process restarted"
		 ;;
	*)	
		echo "Usage: manage_my_process {start|stop|restart}"
		exit 1
		;;
esac
exit 0
