#!/usr/bin/env bash
# Write a Bash script that displays:
To infinity and beyond indefinitely

function sigterm_handler() {
	echo "I am invincible!!!"
	exit 0
}

trap 'sigterm_handler'  SIGTERM

while true; do
	echo "To infinity and beyond"
	sleep 2
done
